[custom]
;Charli整合的Mihomo Clash规则
;UPDATED: 2026.02.18 17:03

;去广告：支持
;Steam下载分流为国区，社区与商店默认Proxy
;不包含中国IPV4与IPV6分流
;不包含GFW分流，依赖路由GeoSite及Geoip


;设置规则标志位
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Ban.list
ruleset=🔗 DNS,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/DNS.list
ruleset=🖥️ VPS,https://gist.githubusercontent.com/Charlizsz/e3cbc442761339caa5885740d9046976/raw/Private.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Direct.list
ruleset=🍎 iCloud媒体,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/iCloud.list
ruleset=🏎️ F1TV,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/F1TV.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/AppleDirect.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/AppleDirect.list
ruleset=🌐 Apple Intelligence,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/AppleIntelligence.list
ruleset=☁️ Cloudflare认证,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/CloudflareChallenges.list
ruleset=🕸 OpenAI,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/OpenAI.list
ruleset=💥 Cluade,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Claude.list
ruleset=♊️ Gemini,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Gemini.list
ruleset=🤖 Copilot,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Copilot.list
ruleset=💬 AI平台,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/AI.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/Clash/non_ip/reject.txt
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/Clash/non_ip/reject-drop.txt
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/Clash/non_ip/reject-no-drop.txt
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/Clash/non_ip/reject-url-regex.txt
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/Clash/ip/reject.txt
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=📢 谷歌服务,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/GoogleService.list
ruleset=Ⓜ️ 微软直连,https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/Clash/non_ip/microsoft_cdn.txt
ruleset=Ⓜ️ OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/master/Clash/non_ip/microsoft.txt
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/refs/heads/master/AppleDirectFallback.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🟠 Reddit,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Reddit.list
ruleset=♾️ Meta系,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Instagram.list
ruleset=♾️ Meta系,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Whatsapp/Whatsapp.list
ruleset=♾️ Meta系,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.list
ruleset=🔮 Oracle,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Oracle.list
ruleset=👨🏻‍💻 Github,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/2KGames/2KGames.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/Steam.list
ruleset=🇭🇰 香港节点,https://raw.githubusercontent.com/Charlizsz/Clash-Rules/master/myHK.list
ruleset=☁️ Cloudflare,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflarecn/Cloudflarecn.list
ruleset=☁️ Cloudflare,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare.list
;ruleset=🎯 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🌏 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba.list
;ruleset=🌏 全球直连,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/AliPay.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/rule/WeChat.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🌏 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🌏 全球直连,[]GEOIP,LAN
ruleset=🌏 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=🎯 节点选择`select`[]🚀 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🏳️‍⚧️ 专线`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]DIRECT
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(SGP|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🏳️‍⚧️ 专线`url-test`(Azure|Oracle|Google|澳门|家宽|2x)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇳 特定专线`url-test`(Azure|Oracle|Google|澳门|家宽|2x)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌐 Apple Intelligence`select`[]🏳️‍⚧️ 专线`[]🇺🇳 特定专线`[]🇨🇳 台湾节点`[]🎯 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 手动切换
custom_proxy_group=🕸 OpenAI`select`[]🏳️‍⚧️ 专线`[]🇺🇳 特定专线`[]🇨🇳 台湾节点`[]🎯 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=💥 Cluade`select`[]🏳️‍⚧️ 专线`[]🇺🇳 特定专线`[]🇨🇳 台湾节点`[]🎯 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=🤖 Copilot`select`[]🎯 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🏳️‍⚧️ 专线`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=♊️ Gemini`select`[]🎯 节点选择`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🏳️‍⚧️ 专线`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=💬 AI平台`select`[]🇨🇳 台湾节点`[]🏳️‍⚧️ 专线`[]🎯 节点选择`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=📲 Telegram`select`[]🇭🇰 香港节点`[]🎯 节点选择`[]🏳️‍⚧️ 专线`[]🇨🇳 台湾节点`[]🚀 手动切换
custom_proxy_group=📹 YouTube`select`[]🇭🇰 香港节点`[]🎯 节点选择`[]🏳️‍⚧️ 专线`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌直连`select`[]🇨🇳 台湾节点`[]🎯 节点选择`[]🇭🇰 香港节点`[]DIRECT`[]🏳️‍⚧️ 专线`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🎯 节点选择`[]🏳️‍⚧️ 专线`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌服务`select`[]🇨🇳 台湾节点`[]🎯 节点选择`[]🇭🇰 香港节点`[]🏳️‍⚧️ 专线`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软直连`select`[]DIRECT`[]🏳️‍⚧️ 专线`[]🎯 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ OneDrive`select`[]🇭🇰 香港节点`[]🏳️‍⚧️ 专线`[]🎯 节点选择`[]DIRECT`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 节点选择`[]🇭🇰 香港节点`[]DIRECT`[]🏳️‍⚧️ 专线`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🎯 节点选择`[]🏳️‍⚧️ 专线`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=🍎 iCloud媒体`select`[]DIRECT`[]🎯 节点选择`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇨🇳 台湾节点`[]🏳️‍⚧️ 专线`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🚀 手动切换
custom_proxy_group=♾️ Meta系`select`[]🇸🇬 新加坡节点`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🏳️‍⚧️ 专线`[]🎯 节点选择`[]🇺🇲 美国节点`[]🚀 手动切换
custom_proxy_group=🔮 Oracle`select`[]🏳️‍⚧️ 专线`[]🎯 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]DIRECT`[]🚀 手动切换
custom_proxy_group=☁️ Cloudflare`select`[]🎯 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🏳️‍⚧️ 专线`[]DIRECT`[]🚀 手动切换
custom_proxy_group=☁️ Cloudflare认证`select`[]🇺🇳 特定专线`[]🏳️‍⚧️ 专线`[]🎯 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]DIRECT`[]🚀 手动切换
custom_proxy_group=👨🏻‍💻 Github`select`[]🎯 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🏳️‍⚧️ 专线`[]🚀 手动切换
custom_proxy_group=🟠 Reddit`select`[]🇸🇬 新加坡节点`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🎯 节点选择`[]🏳️‍⚧️ 专线`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=🏎️ F1TV`select`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🎯 节点选择`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=🎥 Netflix`select`[]🇭🇰 香港节点`[]🎯 节点选择`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🎯 节点选择`[]🇭🇰 香港节点`[]🏳️‍⚧️ 专线`[]🇸🇬 新加坡节点`[]🇺🇲 美国节点`[]🚀 手动切换
custom_proxy_group=🖥️ VPS`select`[]DIRECT`[]🎯 节点选择`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=🔗 DNS`select`[]🎯 节点选择`[]DIRECT`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🌏 全球直连`select`[]DIRECT`[]🎯 节点选择`[]🏳️‍⚧️ 专线
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 节点选择`[]🏳️‍⚧️ 专线`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 新加坡节点`[]🚀 手动切换
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
